import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import type { AppProps } from 'next/app';
import { Amplify } from 'aws-amplify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

Amplify.configure({
	API: {
		GraphQL: {
			endpoint: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT as string,
			region: 'ap-northeast-1',
			apiKey: process.env.NEXT_PUBLIC_API_KEY,
			defaultAuthMode: 'apiKey',
		},
	},
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
